[package]
name = "lightspeed_email"
license = "MIT"
version = "0.34.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
lightspeed_core = { version = "0.34.0", path = "../core" }
async-trait = "0.1"
lettre = { version = "0.10.0-rc.1", default-features = false , features = ["smtp-transport", "builder", "hostname", "r2d2", "rustls-tls"]}
log = "0.4"
parking_lot = "0.11"
serde = { version = "1.0" , features = ["derive", "rc"] }
structopt = "0.3"
tokio = { version = "0.2" , features = ["blocking"] }

[dev-dependencies]
testcontainers = "0.11"
tokio = { version = "0.2" , features = ["full"] }

lightspeed_logger = { version = "0.34.0", path = "../logger" }

