[package]
name = "lightspeed_email"
license = "MIT"
version = "0.33.4"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
lightspeed_core = { version = "0.33.4", path = "../core" }
async-trait = "0.1"
lettre = { version = "0.9" , features = ["smtp-transport"] }
lettre_email = "0.9"
native-tls = "0.2"
log = "0.4"
parking_lot = "0.11"
serde = { version = "1.0" , features = ["derive", "rc"] }
structopt = "0.3"
tokio = { version = "0.2" , features = ["blocking"] }

[dev-dependencies]
testcontainers = "0.11"
tokio = { version = "0.2" , features = ["full"] }

lightspeed_logger = { version = "0.33.4", path = "../logger" }

[features]
vendored = ["native-tls/vendored"]