[package]
name = "lightspeed_email"
license = "MIT"
version = "0.1.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
edition = "2018"

[dependencies]
lightspeed_core = { version = "0.1", path = "../core" }
lettre = "0.9"
lettre_email = "0.9"
native-tls = "0.2.3"
log = "0.4"
parking_lot = "0.10"
serde = { version = "1.0" , features = ["rc"] }
serde_derive = "1"
structopt = "0.3"


[dev-dependencies]
lazy_static = "1.4"
testcontainers = "0.9"

lightspeed_logger = { version = "0.1", path = "../logger" }