[package]
name = "lightspeed_auth"
license = "MIT"
version = "0.1.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
edition = "2018"

[dependencies]
lightspeed_core = { version = "0.1", path = "../core" }
bcrypt = "0.6.0"
c3p0 = { version = "0.42", features = ["pg_015_migrate"] }
log = "0.4"
serde = { version = "1.0" , features = ["rc"] }
serde_derive = "1"
serde_json = "1"
structopt = "0.3"

# See
#typescript-definitions = "0.1.10"
typescript-definitions = {git = "https://github.com/ufoscout/typescript-definitions.git", branch = "no-debug-attrs"}

[dev-dependencies]
lazy_static = "1.3"
maybe-single = "0.7"
testcontainers = "0.8"

lightspeed_logger = { version = "0.1", path = "../logger" }