[package]
name = "lightspeed_auth"
license = "MIT"
version = "0.18.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
lightspeed_core = { version = "0.18.0", path = "../core" }
async-trait = "0.1.29"
bcrypt = "0.8.0"
c3p0 = { version = "0.60.0", features = ["postgres_migrate"] }
log = "0.4"
serde = { version = "1.0" , features = ["derive", "rc"] }
serde_json = "1"
structopt = "0.3"

# See
#typescript-definitions = "0.1.10"
typescript-definitions = {package = "typescript-definitions-ufo-patch", version = "0.1.10"}

[dev-dependencies]
futures = "0.3"
lightspeed_logger = { version = "0.18.0", path = "../logger" }
maybe-single = "0.12"
once_cell = "1.4"
testcontainers = "0.10"
tokio = { version = "0.2", features = ["rt-threaded"] }
