[package]
name = "lightspeed_auth"
license = "MIT"
version = "0.49.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []


[dependencies]
lightspeed_core = { version = "0.49.0", path = "../core", features = ["c3p0"] }
async-trait = "0.1"
bcrypt = "0.12"
c3p0 = { version = "0.64", features = ["postgres_migrate"] }
log = "0.4"
poem-openapi = { version = "1.3", optional = true }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1"
strum = { version = "0.24", features = ["derive"] }


[dev-dependencies]
config = "0.12"
lightspeed_logger = { version = "0.49.0", path = "../logger" }
maybe-single = { version = "0.15.0", features =["async"] }
once_cell = "1"
testcontainers = "0.12"
tokio = { version = "1", features = ["rt-multi-thread"] }

[features]
default = []
poem_openapi = ["dep:poem-openapi"]