[package]
name = "lightspeed_auth"
license = "MIT"
version = "0.1.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
err-derive = "0.1"
log = "0.4"
structopt = "0.2"

ls_core = { version = "0.1", package = "lightspeed_core", path = "../core" }

[dev-dependencies]
actix-service = "0.4"
jsonwebtoken = "6.0"
lazy_static = "1.0"

ls_logger = { version = "0.1", package = "lightspeed_logger", path = "../logger" }