[package]
name = "lightspeed_auth"
license = "MIT"
version = "0.32.1"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
lightspeed_core = { version = "0.32.1", path = "../core" }
async-trait = "0.1"
bcrypt = "0.9"
c3p0 = { version = "0.61.0", features = ["postgres_migrate"] }
log = "0.4"
serde = { version = "1.0" , features = ["derive", "rc"] }
serde_json = "1"
structopt = "0.3"
strum = "0.20"
strum_macros = "0.20"

# See
#typescript-definitions = "0.1.10"
typescript-definitions = {package = "typescript-definitions-ufo-patch", version = "0.1.11"}

[dev-dependencies]
futures = "0.3"
lightspeed_logger = { version = "0.32.1", path = "../logger" }
maybe-single = { version = "0.13.2", features =["tokio_02"] }
once_cell = "1.5"
testcontainers = "0.11"
tokio = { version = "0.2", features = ["rt-threaded"] }
