[package]
name = "lightspeed_auth"
license = "MIT"
version = "0.2.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
lightspeed_core = { version = "0.2.0", path = "../core" }
async-trait = "0.1.29"
bcrypt = "0.6.0"
c3p0 = { version = "0.44", features = ["pg_async_migrate"],  path = "../../../github_ufoscout/c3p0/c3p0" }
log = "0.4"
serde = { version = "1.0" , features = ["rc"] }
serde_derive = "1"
serde_json = "1"
structopt = "0.3"

# See
#typescript-definitions = "0.1.10"
typescript-definitions = {package = "typescript-definitions-ufo-patch", version = "0.1.10"}

[dev-dependencies]
futures = "0.3"
lightspeed_logger = { version = "0.2.0", path = "../logger" }
lazy_static = "1.3"
maybe-single = { version = "0.9.2" } #, path = "../../../github_ufoscout/maybe-single" }
once_cell = "1.3"
testcontainers = "0.9"
tokio = { version = "0.2", features = ["full"] }
