[package]
name = "lightspeed_auth"
license = "MIT"
version = "0.31.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
lightspeed_core = { version = "0.31.0", path = "../core" }
async-trait = "0.1"
bcrypt = "0.9"
c3p0 = { version = "0.62.0", features = ["postgres_migrate"] }
log = "0.4"
serde = { version = "1.0" , features = ["derive", "rc"] }
serde_json = "1"
structopt = "0.3"
strum = { version = "0.20" , features = ["derive"] }

# See
#typescript-definitions = "0.1.10"
typescript-definitions = {package = "typescript-definitions-ufo-patch", version = "0.1.11"}

[dev-dependencies]
lightspeed_logger = { version = "0.31.0", path = "../logger" }
maybe-single = "0.12"
once_cell = "1.5"
testcontainers = "0.11"
tokio = { version = "1", features = ["rt-multi-thread"] }
