[package]
name = "lightspeed_auth"
license = "MIT"
version = "0.1.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
c3p0 = { version = "0.5.1", features = ["pg"] }
c3p0_migrate = { version = "0.5.1", features = ["pg"] }
err-derive = "0.1"
include_dir="0.2"
log = "0.4"
structopt = "0.2"

ls_core = { version = "0.1", package = "lightspeed_core", path = "../core" }

[dev-dependencies]
lazy_static = "1.0"

ls_logger = { version = "0.1", package = "lightspeed_logger", path = "../logger" }