[package]
name = "lightspeed_auth"
license = "MIT"
version = "0.44.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
lightspeed_core = { version = "0.44.0", path = "../core" }
async-trait = "0.1"
bcrypt = "0.10"
c3p0 = { version = "0.64.0", features = ["postgres_migrate"] }
clap = { version = "3.0.0-beta.5", default-features = false, features = ["derive", "env", "std"] }
log = "0.4"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1"
strum = { version = "0.23", features = ["derive"] }

# See
#typescript-definitions = "0.1.10"
typescript-definitions = { package = "typescript-definitions-ufo-patch", version = "0.1.11" }

[dev-dependencies]
lightspeed_logger = { version = "0.44.0", path = "../logger" }
maybe-single = { version = "0.15.0", features =["async"] }
once_cell = "1"
testcontainers = "0.12"
tokio = { version = "1", features = ["rt-multi-thread"] }
