[package]
name = "lightspeed_file_store"
license = "MIT"
version = "0.34.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
lightspeed_core = { version = "0.34.0", path = "../core" }
async-trait = "0.1"
c3p0 = { version = "0.62.0", features = ["postgres_migrate"] }
log = "0.4"
serde = { version = "1.0" , features = ["derive", "rc"] }
serde_json = "1"
structopt = "0.3"
strum = { version = "0.20" , features = ["derive"] }
tokio = { version = "1" , features = ["fs", "io-util"] }

actix-files = { version = "0.6.0-beta.4", optional = true }
actix-web = { version = "4.0.0-beta.5", optional = true }
mime = { version = "0.3", optional = true }
mime_guess = { version = "2.0", optional = true }

[dev-dependencies]
lightspeed_logger = { version = "0.34.0", path = "../logger" }
maybe-single = { version = "0.15.0", features =["async"] }
once_cell = "1.5"
rand = "0.8"
tempfile = "3"
testcontainers = "0.12"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[features]
default = []

actix_web_4 = ["actix-files", "actix-web", "lightspeed_core/actix_web_4", "mime", "mime_guess"]