[package]
name = "lightspeed_file_store"
license = "MIT"
version = "0.21.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
lightspeed_core = { version = "0.21.0", path = "../core" }
async-trait = "0.1.29"
c3p0 = { version = "0.60.1", features = ["postgres_migrate"] }
log = "0.4"
serde = { version = "1.0" , features = ["derive", "rc"] }
serde_json = "1"
structopt = "0.3"
strum = "0.19.0"
strum_macros = "0.19.0"
tokio = { version = "0.2" , features = ["fs", "io-util"] }

actix-files = { version = "0.3.0", optional = true }
actix-web = { version = "3.0.0", optional = true }
mime = { version = "0.3.16", optional = true }
mime_guess = { version = "2.0.3", optional = true }

[dev-dependencies]
lightspeed_logger = { version = "0.21.0", path = "../logger" }
futures = "0.3"
maybe-single = "0.12"
once_cell = "1.4"
rand = "0.7"
tempfile = "3"
testcontainers = "0.11"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }

[features]
default = []

actix_web_3 = ["actix-files", "actix-web", "lightspeed_core/actix_web_3", "mime", "mime_guess"]