[package]
name = "lightspeed_file_store"
license = "MIT"
version = "0.33.3"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
lightspeed_core = { version = "0.33.3", path = "../core" }
async-trait = "0.1"
c3p0 = { version = "0.61.0", features = ["postgres_migrate"] }
log = "0.4"
serde = { version = "1.0" , features = ["derive", "rc"] }
serde_json = "1"
structopt = "0.3"
strum = "0.20"
strum_macros = "0.20"
tokio = { version = "0.2" , features = ["fs", "io-util"] }

actix-files = { version = "0.4.0", optional = true }
actix-web = { version = "3.2.0", optional = true }
mime = { version = "0.3", optional = true }
mime_guess = { version = "2.0", optional = true }

[dev-dependencies]
lightspeed_logger = { version = "0.33.3", path = "../logger" }
futures = "0.3"
maybe-single = { version = "0.13.2", features =["tokio_02"] }
once_cell = "1.5"
rand = "0.8"
tempfile = "3"
testcontainers = "0.11"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }

[features]
default = []

actix_web_3 = ["actix-files", "actix-web", "lightspeed_core/actix_web_3", "mime", "mime_guess"]