[package]
name = "lightspeed_file_store"
license = "MIT"
version = "0.44.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
lightspeed_core = { version = "0.44.0", path = "../core" }
async-trait = "0.1"
c3p0 = { version = "0.64.0", features = ["postgres_migrate"] }
clap = { version = "3.0.0-beta.5", default-features = false, features = ["derive", "env", "std"] }
log = "0.4"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1"
strum = { version = "0.23", features = ["derive"] }
tokio = { version = "1", features = ["fs", "io-util"] }

actix-files = { version = "0.6.0-beta.8", optional = true }
actix-web = { version = "4.0.0-beta.11", optional = true }
mime = { version = "0.3", optional = true }
mime_guess = { version = "2.0", optional = true }

axum_ext = { package = "axum", version = "0.4", optional = true }
tokio-util = { version = "0.6", optional = true, features = ["io"] }


[dev-dependencies]
actix-rt = "2"
lightspeed_logger = { version = "0.44.0", path = "../logger" }
maybe-single = { version = "0.15.0", features =["async"] }
once_cell = "1.5"
rand = "0.8"
tempfile = "3"
testcontainers = "0.12"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tower = "0.4"

[features]
default = []

actix_web_4 = ["actix-files", "actix-web", "lightspeed_core/actix_web_4", "mime", "mime_guess"]
axum = ["axum_ext", "lightspeed_core/axum", "mime_guess", "tokio-util"]