[package]
name = "lightspeed_file_store"
license = "MIT"
version = "0.13.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
lightspeed_core = { version = "0.13.0", path = "../core" }
async-trait = "0.1.29"
c3p0 = { version = "0.53.0", features = ["pg_migrate"] }
log = "0.4"
serde = { version = "1.0" , features = ["derive", "rc"] }
serde_json = "1"
structopt = "0.3"
tokio = { version = "0.2" , features = ["fs", "io-util"] }

# feature 'actix-web'
actix-files = { version = "0.2", optional = true }
actix_web_external = {package = "actix-web", version = "2.0.0", optional = true }
http = { version = "0.2", optional = true }
futures = { version = "0.3.4", optional = true }

[dev-dependencies]
futures = "0.3"
lightspeed_logger = { version = "0.13.0", path = "../logger" }
maybe-single = "0.12"
once_cell = "1.4"
rand = "0.7"
tempfile = "3"
testcontainers = "0.9"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }

[features]
default = []

actix-web = ["actix-files", "actix_web_external", "http", "lightspeed_core/actix-web", "futures"]