[package]
name = "lightspeed_file_store"
license = "MIT"
version = "0.4.1"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
lightspeed_core = { version = "0.4.1", path = "../core" }
async-trait = "0.1.29"
c3p0 = { version = "0.50.1", features = ["pg_migrate"] }
log = "0.4"
serde = { version = "1.0" , features = ["rc"] }
serde_derive = "1"
serde_json = "1"
structopt = "0.3"


[dev-dependencies]
futures = "0.3"
lightspeed_logger = { version = "0.4.1", path = "../logger" }
maybe-single = "0.12"
once_cell = "1.3"
testcontainers = "0.9"
tokio = { version = "0.2", features = ["rt-threaded"] }
