[package]
name = "lightspeed_file_store"
license = "MIT"
version = "0.17.2"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
lightspeed_core = { version = "0.17.2", path = "../core" }
async-trait = "0.1.29"
c3p0 = { version = "0.60.0", features = ["postgres_migrate"] }
log = "0.4"
serde = { version = "1.0" , features = ["derive", "rc"] }
serde_json = "1"
structopt = "0.3"
tokio = { version = "0.2" , features = ["fs", "io-util"] }

[dev-dependencies]
futures = "0.3"
lightspeed_logger = { version = "0.17.2", path = "../logger" }
maybe-single = "0.12"
once_cell = "1.4"
rand = "0.7"
tempfile = "3"
testcontainers = "0.10"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }

