[package]
name = "lightspeed_core"
license = "MIT"
version = "0.1.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
chrono = "0.4"
err-derive= "0.1"
jsonwebtoken = "6.0"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2"

ls_logger = { version = "0.1", package = "lightspeed_logger", path = "../logger" }

[dev-dependencies]
actix-service = "0.4"
lazy_static = "1.0"
