[package]
name = "lightspeed_core"
version = "0.1.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0"
coreutils_json = "0.5"
coreutils_jwt = "0.5"
coreutils_logger = "0.5"
coreutils_module = "0.5"
log = "0.4"
structopt = "0.2"
