[package]
name = "lightspeed_core"
license = "MIT"
version = "0.1.1"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
c3p0_common = { version = "0.43" }
chrono = "0.4"
jsonwebtoken = "7.0"
log = "0.4"
rand = "0.7"
serde = { version = "1.0" , features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.3"
strum = "0.18.0"
strum_macros = "0.18.0"
thiserror = "1.0"
uuid = { version = "0.8", features = ["v4"] }
validator = "0.10"

# See
#typescript-definitions = "0.1.10"
typescript-definitions = {package = "typescript-definitions-ufo-patch", version = "0.1.10"}

actix_web_external = {package = "actix-web", version = "2.0.0", optional = true }

[dev-dependencies]
actix-service = "1.0.1"
actix-rt = "1.0.0"
lazy_static = "1.4"
lightspeed_logger = { version = "0.1", path = "../logger" }

[features]
default = []

actix-web = ["actix_web_external"]