[package]
name = "lightspeed_core"
license = "MIT"
version = "0.19.1"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
async-trait = "0.1"
c3p0_common = { version = "0.60.0" }
chrono = "0.4"
jsonwebtoken = "7.1"
log = "0.4"
rand = "0.7"
serde = { version = "1.0" , features = ["derive", "rc"] }
serde_json = "1.0"
structopt = "0.3"
strum = "0.19.0"
strum_macros = "0.19.0"
thiserror = "1.0"
uuid = { version = "0.8", features = ["v4"] }
validator = "0.11"

# See
#typescript-definitions = "0.1.10"
typescript-definitions = {package = "typescript-definitions-ufo-patch", version = "0.1.11"}

actix_web_3_ext = {package = "actix-web", version = "3.0.0", optional = true }
warp_external = {package = "warp", version = "0.2.5", optional = true }

[dev-dependencies]
# Could be removed. See https://github.com/actix/actix-web/issues/1669
actix-rt = "1.1.1"

lightspeed_logger = { version = "0.19.1", path = "../logger" }
parking_lot = "0.11"
typemap = "0.3.3"
tokio = { version = "0.2.0", features = ["full"] }

[features]
default = []

actix_web_3 = ["actix_web_3_ext"]
warp = ["warp_external"]