[package]
name = "lightspeed_core"
license = "MIT"
version = "0.40.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
async-trait = "0.1"
c3p0_common = { version = "0.63.0" }
chrono = "0.4"
jsonwebtoken = "7.1"
log = "0.4"
rand = "0.8"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
structopt = "0.3"
strum = { version = "0.21", features = ["derive"] }
uuid = { version = "0.8", features = ["v4"] }
validator = "0.14"

# See
#typescript-definitions = "0.1.10"
typescript-definitions = { package = "typescript-definitions-ufo-patch", version = "0.1.11" }

actix_web_4_ext = { package = "actix-web", version = "4.0.0-beta.8", optional = true }
axum_ext = { package = "axum", version = "0.2", optional = true }
http = { version = "0.2", optional = true }

[dev-dependencies]
actix-rt = "2"
hyper = "0.14"
lightspeed_logger = { version = "0.40.0", path = "../logger" }
tokio = { version = "1", features = ["macros", "rt", "sync"] }
tower = "0.4"

[features]
default = []

axum = ["axum_ext", "web"]
actix_web_4 = ["actix_web_4_ext", "web"]
web = ["http"]