[package]
name = "lightspeed_core"
license = "MIT"
version = "0.34.4"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
async-trait = "0.1"
c3p0_common = { version = "0.62.0" }
chrono = "0.4"
jsonwebtoken = "7.1"
log = "0.4"
rand = "0.8"
serde = { version = "1.0" , features = ["derive", "rc"] }
serde_json = "1.0"
structopt = "0.3"
strum = { version = "0.20" , features = ["derive"] }
thiserror = "1.0"
uuid = { version = "0.8", features = ["v4"] }
validator = "0.13"

# See
#typescript-definitions = "0.1.10"
typescript-definitions = {package = "typescript-definitions-ufo-patch", version = "0.1.11"}

actix_web_4_ext = {package = "actix-web", version = "4.0.0-beta.5", optional = true }
warp_03_ext = {package = "warp", version = "0.3", optional = true }

[dev-dependencies]
actix-rt = "2"
lightspeed_logger = { version = "0.34.4", path = "../logger" }
tokio = { version = "1", features = ["macros", "rt", "sync"] }

[features]
default = []

actix_web_4 = ["actix_web_4_ext"]
warp_03 = ["warp_03_ext"]