[package]
name = "lightspeed_scheduler"
license = "MIT"
version = "0.6.2"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "An in-process scheduler for periodic jobs. Schedule lets you run Rust functions on a cron-like schedule."
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = ["schedule", "cron", "job", "periodic"]

[dependencies]
cron = "0.6"
chrono = "0.4"
chrono-tz = "0.5"
log = "0.4"
parking_lot = "0.10.0"
thiserror = "1.0"
time = "0.1"
tracing = "0.1.13"
tracing-futures = "0.2.3"