[package]
name = "lightspeed_scheduler"
license = "MIT"
version = "0.30.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "An in-process scheduler for periodic jobs. Schedule lets you run Rust functions on a cron-like schedule."
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = ["schedule", "cron", "job", "periodic"]

[dependencies]
atomic = "0.5"
cron = "0.7.0"
chrono = "0.4"
chrono-tz = "0.5"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
log = "0.4"
thiserror = "1.0"
tokio = { version = "1", features = ["sync", "time"] }
tracing = "0.1"
tracing-futures = "0.2"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
