[package]
name = "lightspeed_cms"
license = "MIT"
version = "0.49.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
lightspeed_cache = { version = "0.49.0", path = "../cache" }
lightspeed_core = { version = "0.49.0", path = "../core", features = ["c3p0"] }
async-trait = "0.1"
c3p0 = { version = "0.64", features = ["postgres_migrate"] }
log = "0.4"
once_cell = "1"
regex = "1"
serde = { version = "1", features = ["derive", "rc"] }


[dev-dependencies]
config = "0.12"
lightspeed_logger = { version = "0.49.0", path = "../logger" }
maybe-single = { version = "0.15.0", features =["async"] }
testcontainers = "0.12"
tokio = { version = "1", features = ["rt-multi-thread"] }
