[package]
name = "lightspeed_cms"
license = "MIT"
version = "0.1.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
edition = "2018"

[dependencies]
lightspeed_core = { version = "0.1", path = "../core" }
actix-web = "1.0"
c3p0 = { version = "0.22", features = ["pg_migrate"] }
#c3p0 = { version = "0.20", features = ["pg_migrate"], path = "../../../github_ufoscout/c3p0/c3p0"}
chashmap = "2.2" # to be replaced with crossbean-skiplist or another lock free map
err-derive = "0.1"
include_dir="0.2"
lazy_static = "1.3"
log = "0.4"
regex = "1.3"
serde = "1"
serde_derive = "1"
structopt = "0.2"


[dev-dependencies]
maybe-single = "0.4"
maplit = "1"
testcontainers = "0.8"

ls_logger = { version = "0.1", package = "lightspeed_logger", path = "../logger" }