[package]
name = "lightspeed_cms"
license = "MIT"
version = "0.1.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
edition = "2018"

[dependencies]
lightspeed_core = { version = "0.1", path = "../core" }
c3p0 = { version = "0.28", features = ["pg_migrate"] }
chashmap = "2.2" # to be replaced with crossbean-skiplist or another lock free map
include_dir="0.4"
lazy_static = "1.4"
log = "0.4"
regex = "1.3"
serde = "1"
serde_derive = "1"
structopt = "0.3"


[dev-dependencies]
maybe-single = "0.4"
maplit = "1"
testcontainers = "0.8"

ls_logger = { version = "0.1", package = "lightspeed_logger", path = "../logger" }