[package]
name = "lightspeed_cms"
license = "MIT"
version = "0.2.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
lightspeed_cache = { version = "0.2.0", path = "../cache" }
lightspeed_core = { version = "0.2.0", path = "../core" }
async-trait = "0.1.29"
c3p0 = { version = "0.50.0", features = ["pg_migrate"] }
lazy_static = "1.4"
log = "0.4"
regex = "1.3"
serde = "1"
serde_derive = "1"
structopt = "0.3"


[dev-dependencies]
lightspeed_logger = { version = "0.2.0", path = "../logger" }
maybe-single = { version = "0.10.1", features = ["async"]}
maplit = "1"
testcontainers = "0.9"
tokio = { version = "0.2", features = ["full"] }
