[package]
name = "lightspeed_cms"
license = "MIT"
version = "0.34.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
lightspeed_cache = { version = "0.34.0", path = "../cache" }
lightspeed_core = { version = "0.34.0", path = "../core" }
async-trait = "0.1"
c3p0 = { version = "0.62.0", features = ["postgres_migrate"] }
log = "0.4"
once_cell = "1"
regex = "1"
serde = { version = "1" , features = ["derive", "rc"] }
structopt = "0.3"


[dev-dependencies]
lightspeed_logger = { version = "0.34.0", path = "../logger" }
maybe-single = { version = "0.14.0", features =["tokio_1"] }
maplit = "1"
testcontainers = "0.12"
tokio = { version = "1", features = ["rt-multi-thread"] }
