[package]
name = "lightspeed_cms"
license = "MIT"
version = "0.1.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
edition = "2018"

[dependencies]
lightspeed_cache = { version = "0.1", path = "../cache" }
lightspeed_core = { version = "0.1", path = "../core" }
c3p0 = { version = "0.43", features = ["pg_015_migrate"] }
lazy_static = "1.4"
log = "0.4"
regex = "1.3"
serde = "1"
serde_derive = "1"
structopt = "0.3"


[dev-dependencies]
maybe-single = "0.8.1"
maplit = "1"
testcontainers = "0.9"

ls_logger = { version = "0.1", package = "lightspeed_logger", path = "../logger" }