[package]
name = "lightspeed_logger"
license = "MIT"
version = "0.23.1"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
log = "0.4"
rand = "0.7.3"
thiserror = "1.0"
tracing = "0.1.16"
tracing-futures = "0.2.3"
tracing-subscriber = "0.2"
structopt = "0.3"

[dev-dependencies]
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }