[package]
name = "lightspeed_logger"
license = "MIT"
version = "0.40.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
clap = { version = "3.0.0-beta.4", default-features = false, features = ["derive", "env", "std"] }
log = "0.4"
rand = "0.8"
thiserror = "1.0"
tracing = "0.1"
tracing-appender = "0.1"
tracing-futures = "0.2"
tracing-log = "0.1"
tracing-subscriber = "0.2"


[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }