[package]
name = "lightspeed_logger"
license = "MIT"
version = "0.1.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "Logger configuration based on fern."
edition = "2018"

[dependencies]
chrono = "0.4"
fern = "0.6.0"
log = "0.4"
structopt = "0.3"
thiserror = "1.0"
