[package]
name = "lightspeed_logger"
license = "MIT"
version = "0.2.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]
description = "LightSpeed"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/LightHero/lightspeed"
repository = "https://github.com/LightHero/lightspeed"
keywords = []

[dependencies]
chrono = "0.4"
fern = "0.6.0"
log = "0.4"
structopt = "0.3"
thiserror = "1.0"
